### ISSUE TITLE
80% test coverage for back end.

### ISSUE THREAD

**Issue by Lieutenant-Lewd-Strawberry** [cs361fall2018/project-team-38#54]
All back end Java in the models package needs 80% test coverage. Anyone working on the back end should make adequate testing for what they implement.

Estimate: End of Milestone Sprint 3

**Comment by jacoalex** [comment]
So how much test coverage do we have right now? @Lieutenant-Lewd-Strawberry

**Comment by Lieutenant-Lewd-Strawberry** [comment]
I have no idea, it was just a requirement to be at 80%. I have no idea how to actually check it though, google was saying it is a plugin and a bunch of settings with the debugger to get that information. I did all my code front end in the JS instead of the backend and the requirements specifically noted that frontend JS does not need to be tested.

**Comment by Lieutenant-Lewd-Strawberry** [comment]
Completed.
