### ISSUE TITLE
Implement Submarine

### ISSUE THREAD

**Issue by Lieutenant-Lewd-Strawberry** [cs361fall2018/project-team-38#62]
Implement the submarine feature to the specifications of the user stories. 

Estimate: 1 day

**Comment by Lieutenant-Lewd-Strawberry** [comment]
Completed

**Comment by jacoalex** [comment]
It looks like we don't have a way to have the sub be place on the surface or under the water. Right now it just defaults to being underwater. I think that will have to be good enough. I did fix the space laser though, so only after the first ship is sunk can you hit the sub. See issue: #63
