### ISSUE TITLE
Implement New Bomb

### ISSUE THREAD

**Issue by Lieutenant-Lewd-Strawberry** [cs361fall2018/project-team-38#63]
Implement the new bomb type to the specifications of the user stories.
Estimate: 1 day

**Comment by Lieutenant-Lewd-Strawberry** [comment]
If someone feels like figuring out how to get the submarine to only be hit when submerged after the first ship is sunk, feel free.

**Comment by jacoalex** [comment]
This isn't done...?

**Comment by jacoalex** [comment]
All finished.
