### ISSUE TITLE
Push the assignment by 1 or 2 days?

### ISSUE THREAD

**Issue by jacoalex** [cs361fall2018/project-team-38#66]
I really would like to help on this, I've just be soo busy this week and I have a bunch of stuff do tonight. I'm pretty sure in this class we get to turn in one assignment 2 days late. Since this is our last assignment any chance we could do that for this one? I want to help out on it but I just can't today. I'll be available all day tomorrow to work on it. Is it cool if I request 2 extra days for this assignment? @Lieutenant-Lewd-Strawberry and @smithal5 ? Thanks.

**Comment by Lieutenant-Lewd-Strawberry** [comment]
Im okay with it if you want, I got the fleet movement working I think as far as I know.

**Comment by Lieutenant-Lewd-Strawberry** [comment]
Might want to contact the prof or TAs before 5:00pm though, they have to know before the due date according to the syllabus.

**Comment by jacoalex** [comment]
He just responded back, so we are good to turn it in Sunday Night.
