### ISSUE TITLE
UML Designs 

### ISSUE THREAD

**Issue by jacoalex** [cs361fall2018/project-team-38#69]
We all have to make UML diagrams:

Create UML Class Diagrams. Create 4 different UML diagrams detailing your Battleship game. The first Class Diagram shows the structure of the system before the refactoring (see below). For the Class Diagram (After), State Diagram (After), and Sequence Diagram (After), these diagrams should include the results from both the Object-Oriented Design refactoring described below, as well as the implementation of the new feature described in the Introduction section above. Add these diagrams to wiki pages on your team's GitHub repository, and include the name of the team member that created each diagram.

- Class Diagram (Before): UML Class diagram detailing the structure of your Battleship game at the end of Sprint 3. This should include any changes made in the implementation of the Feature Backlog described above.
- Class Diagram (After): UML Class diagram detailing the structure of your Battleship game at the end of Sprint 4.
- State Diagram (After): UML State diagram detailing each state that could possibly be reached in your Battleship game at the end of Sprint 4.
- Sequence Diagram (After): UML Sequence diagram illustrating the typical case in which a player interacts with your Battleship game at the end of Sprint 4.

Note: If you team only has 3 team members, you can drop the State Diagram.

**Comment by jacoalex** [comment]
I think we can drop the state diagram in this case.

**Comment by Lieutenant-Lewd-Strawberry** [comment]
Do the Sequence one, I got the Before and After done already.

**Comment by jacoalex** [comment]
What tool did you use for those? I just want mine to match.

**Comment by Lieutenant-Lewd-Strawberry** [comment]
https://www.draw.io/

**Comment by jacoalex** [comment]
We also need to add our names to the wiki, per the instructions.
